# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Arty-S7-25-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_0_2/design_1_UART_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_UART_0_2 || ORIG_REF_NAME==design_1_UART_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_to_ram_0_0/design_1_to_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_to_ram_0_0 || ORIG_REF_NAME==design_1_to_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAM64_0_0/design_1_RAM64_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_RAM64_0_0 || ORIG_REF_NAME==design_1_RAM64_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_4/design_1_system_ila_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_4 || ORIG_REF_NAME==design_1_system_ila_0_4} -quiet] -quiet

# XDC: c:/Users/dlnmt/man_bram/man_bram.gen/sources_1/bd/design_1/design_1_ooc.xdc
